set nocompatible              " be iMproved, required
filetype off                  " required
:syntax on
:inoremap { {}<Esc>i
:inoremap ( ()<Esc>i
set history=1000
set ignorecase
set smartcase
set incsearch
set title
set hlsearch 
set incsearch
filetype plugin indent on
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set number
set ruler
set foldenable
set autochdir
set cursorline
:inoremap jk <Esc>
set showmode
set hidden 
set mouse=a
set noswapfile
set cindent
set nowrap
let mapleader = "\<Space>"
nnoremap <leader>s :set spell!
:inoremap jj <Esc>/[)}"'\]>]<CR>:nohl<CR>a
set encoding=utf-8
execute pathogen#infect()
