#This gets called from .profile when a new shells gets spawned from macosx 
#and this is the entry level script when a new shell is spawned on a remote linux host
export PATH=/home/y/bin64:$PATH
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi

source ~/.bashrc

export PATH="/usr/local/bin:$PATH"
